/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_VentanaPersonas;

/**
 *
 * @author Casa
 */
public class FRM_VentanaPersonas extends javax.swing.JFrame {

    Controlador_FRM_VentanaPersonas controlador;
    public FRM_VentanaPersonas() {
        initComponents();
        setVisible(false);
        controlador = new Controlador_FRM_VentanaPersonas(this);
        this.panelBotones1.agregarEventos(controlador);
        this.panelInformacion2.agregarEventos(controlador);
    }

    
    public String[] obtenerInformacionAGuardar()
    {
        return this.panelInformacion2.obtenerInformacionAGuardar();
    }
    
    public String devolverCedula()
    {
        return this.panelInformacion2.devolverCedula();
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.panelInformacion2.mostrarInformacion(arreglo);
    }
    
    public void habilitarAgregar()
    {
        this.panelBotones1.habilitarAgregar();
        this.panelInformacion2.habilitarAgregar();
    }
    
    public void habilitarEdicion()
    {
        this.panelInformacion2.habilitarAgregar();
        this.panelBotones1.habilitarEdicion();
    }
    
    public void inicializarGUI()
    {
        this.panelInformacion2.inicializarGUI();
        this.panelBotones1.inicializarGUI();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones1 = new vista.PanelBotones();
        panelInformacion2 = new vista.PanelInformacion();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelInformacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelInformacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelBotones panelBotones1;
    private vista.PanelInformacion panelInformacion2;
    // End of variables declaration//GEN-END:variables
}
